### ISSUE TITLE
Замечания по workshop1

### ISSUE THREAD

**Issue by sergey-shambir** [kvladiimiir/Cpp_Course#2]
Сборка workshop1.4 не удалась
Стоит ознакомиться с документом [Типичные ошибки в лабораторных](https://docs.google.com/document/d/1CdjUuVFGVdE612S40-PdTKZkJbwWlRrNtq1l58cXzMQ/edit?usp=sharing)

Также советую скачать с Github zip-архив с исходным кодом, распаковать и попробовать собрать в терминале Visual Studio Code - так вы увидите ошибки сборки. Скачать можно по кнопке Download ZIP:
![default](https://user-images.githubusercontent.com/1856842/34784562-a50bb6a6-f63f-11e7-90c1-0954572dc685.png)

**Comment by sergey-shambir** [comment]
Я ошибся, всё собирается

**Comment by kvladiimiir** [comment]
Можете проверить пожалуйста sfml3.1 и sfml3.3
Еще, мы с Максимом Гусевым вместе делали в паре!
